# Generated by Django 4.0.5 on 2022-06-26 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='', max_length=50)),
                ('lname', models.CharField(default='', max_length=50)),
                ('email_id', models.EmailField(max_length=50, unique=True)),
                ('phone', models.CharField(default=0, max_length=10, unique=True)),
                ('username', models.CharField(default='', max_length=20, unique=True)),
                ('password', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SellerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='', max_length=50)),
                ('lname', models.CharField(default='', max_length=50)),
                ('email_id', models.EmailField(max_length=50, unique=True)),
                ('phone', models.CharField(default=0, max_length=10, unique=True)),
                ('username', models.CharField(default='', max_length=20, unique=True)),
                ('password', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProductsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('category', models.CharField(default='', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('isAvailable', models.BooleanField(default=False)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=3)),
                ('state', models.CharField(default='', max_length=15)),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.sellerdata')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_date', models.DateTimeField(editable=False)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.productsdata')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_purchased', models.ManyToManyField(blank=True, to='backend.productpurchasehistory')),
            ],
        ),
    ]
