# Generated by Django 4.0.5 on 2022-06-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerdata',
            name='unique_id',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
