# Generated by Django 4.0.5 on 2022-06-25 14:33

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_sellerdata_unique_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='', max_length=50)),
                ('lname', models.CharField(default='', max_length=50)),
                ('email_id', models.EmailField(max_length=50, unique=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(default=0, max_length=128, region=None, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sellerdata',
            name='name',
        ),
        migrations.AddField(
            model_name='sellerdata',
            name='fname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sellerdata',
            name='lname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sellerdata',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default=0, max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='sellerdata',
            name='email_id',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='sellerdata',
            name='unique_id',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='ProductsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('category', models.CharField(default='', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('isAvailable', models.BooleanField(default=False)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=3)),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.sellerdata')),
            ],
        ),
    ]
