# Generated by Django 4.0.5 on 2022-06-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_customerdata_remove_sellerdata_name_sellerdata_fname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerdata',
            name='unique_id',
        ),
        migrations.AlterField(
            model_name='customerdata',
            name='phone',
            field=models.CharField(default=0, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='sellerdata',
            name='phone',
            field=models.CharField(default=0, max_length=10, unique=True),
        ),
    ]
