# Generated by Django 4.0.5 on 2022-06-26 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_customerhistory_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerhistory',
            name='username',
            field=models.CharField(default='', max_length=20),
        ),
    ]
