# Generated by Django 4.0.5 on 2022-06-26 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_customerhistory_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerdata',
            name='GSTIN',
            field=models.CharField(default='', max_length=15, unique=True),
        ),
        migrations.AddField(
            model_name='sellerdata',
            name='PAN',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
