# Generated by Django 4.0.5 on 2022-06-26 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0006_sellerdata_gstin_sellerdata_pan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerdata',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
