# Generated by Django 4.0.5 on 2022-06-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_sellerdata_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerdata',
            name='username',
            field=models.CharField(default='', max_length=20),
        ),
    ]
