# Generated by Django 4.0.5 on 2022-06-26 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_sellerdata_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerdata',
            name='phone',
        ),
    ]
