# Generated by Django 4.0.5 on 2022-06-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_sellerdata_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerdata',
            name='phone',
            field=models.CharField(default=0, max_length=10, unique=True),
        ),
    ]
