# Generated by Django 4.0.5 on 2022-06-26 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_sellerdata_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellerdata',
            old_name='username',
            new_name='credentials',
        ),
        migrations.RemoveField(
            model_name='sellerdata',
            name='email_id',
        ),
        migrations.RemoveField(
            model_name='sellerdata',
            name='password',
        ),
    ]
