# Generated by Django 4.0.5 on 2022-06-26 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0012_rename_username_sellerdata_credentials_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdata',
            name='email_id',
        ),
        migrations.RemoveField(
            model_name='customerdata',
            name='password',
        ),
        migrations.RemoveField(
            model_name='customerdata',
            name='username',
        ),
        migrations.AddField(
            model_name='customerdata',
            name='credentials',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
